monitoring:
    enabled: true
    eve_path: /var/log/suricata/eve.json
    check_interval: 35s # slightly larger than default gomon timewindow of 30s
    default_timeout: 2m
    analysis_timeout: 0 # disable analysis timeout
    alerts:
        - sid: 1000011 # C2 Traffic: C2 Communicates with Sandbox (PSH)
          timeout: 10m
malwarebazaar:
    enabled: true
    api_key: ""
    base_url: https://mb-api.abuse.ch/api/v1/
    sample_dir: data/samples
    watcher:
        enabled: true
        watch_interval: 1h
        instrumentation: /opt/bottle-warden/instrumentation/default.yaml
        sample_timeout: 2m
        sandbox_timeout: 3m
        lookback_hours: 1
        tags:
            - mirai
