monitoring:
    enabled: true
    eve_path: /var/log/suricata/eve.json
    check_interval: 30s
    default_timeout: 2m
    analysis_timeout: 15m
    alerts:
        - sid: 200001
          timeout: 5m
        - sid: 200010
          timeout: 2m
malwarebazaar:
    enabled: true
    api_key: ""
    base_url: https://mb-api.abuse.ch/api/v1/
    sample_dir: data/samples
    watcher:
        enabled: true
        watch_interval: 1h
        instrumentation: /opt/bottle-agent/instrumentation/default.yaml
        sample_timeout: 2m
        sandbox_timeout: 3m
        tags:
            - mirai
